terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.70.0"
    }
  }
  backend "s3" {
    bucket = "nicks-terraform-states"
    key    = "uncomfortable_questions_website/website_domain/terraform.tfstate"
    region = "ap-southeast-2"
  }
}

provider "aws" {
  region = "ap-southeast-2"
  default_tags {
    tags = {
      Project = "Uncomfortable Questions"
    }
  }
}

resource "aws_route53_delegation_set" "name_servers" {
  // Group of 4 name servers, generated by AWS. These four values must be 
  // the same for both the hosted zone and the registered domain, which
  // is a manual step.
  reference_name = "WebsiteDNS"
}
