output "client_id" {
  description = "ID of the Cognito client"
  value       = local.permanent_output.cognito_client_id
}

output "gateway_url" {
  description = "URL for invoking API Gateway."
  value       = module.game.gateway_url
}

output "analytics_gateway_url" {
  description = "URL for invoking analytics API Gateway."
  value       = module.analytics.gateway_url
}

output "public_url" {
  description = "URL of the static website"
  value       = module.s3_bucket.public_url
}

# Save output for using website/app

resource "local_file" "website" {
  content  = <<-EOT
    // This file is automatically generated by terraform
    const clientId = "${local.permanent_output.cognito_client_id}"
    const gatewayUrl = "${module.game.gateway_url}"
  EOT
  filename = "../../../website/js/terraform.js"
}

resource "local_file" "flutter" {
  content  = <<-EOT
    # This file is automatically generated by terraform
    WEBSOCKET_URL="${module.game.gateway_url}"
    ANALYTICS_URL="${module.analytics.gateway_url}"
    COGNITO_USER_POOL="${local.permanent_output.cognito_user_pool_id}"
    COGNITO_CLIENT_ID="${local.permanent_output.cognito_client_id}"
  EOT
  filename = "../../../flutter/.env"
}
